### ISSUE TITLE
add -f -o and -n flags to the subset utility

### ISSUE THREAD

**Issue by zacsketches** [FATHOM5/Seattle_Track_2#20]

**Comment by patrickneise** [comment]
What is the desired functionality of the -n flag?  I have the -f and -o flags added similar to what is in format_time

**Comment by zacsketches** [comment]
@patrickneise thank you!
the -n flag should function so the len(subset) = n.  Most of the AIS files are 1M+ lines long.  So the -n flag will allow the subset tool to build a set to a configurable length.
