### ISSUE TITLE
Delete old data files

### ISSUE THREAD

**Issue by sulliv13** [FATHOM5/Seattle_Track_2#26]
Data Dictionary is mispelled
Files to be deleted
![image](https://user-images.githubusercontent.com/42654871/45784816-0d6c2780-bc1f-11e8-98e2-2add32066275.png)

**Comment by zacsketches** [comment]
@sulliv13 I'm on it.  Love the way you even assigning issues now!

**Comment by zacsketches** [comment]
@sulliv13 all of the files you wanted taken care of are moved out.  Where is "Data Dictionary misspelled"
